---
- name: Configure EC2 Instance
  hosts: ec2
  become: true
  tasks:

    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run Docker hello-world container
      shell: docker run hello-world
